name: Lint
on:
  pull_request:
  push:
    paths:
      - '**.go'
      - 'revive.toml'
      - '.github/workflows/lint.yaml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Install revive-action
        run: go install github.com/cee-dub/revive-action

      - name: Run Revive Action
        run: revive -config revive.toml -formatter ndjson ./... | revive-action

      - name: Check formatting
        run: test -z $(gofmt -l .) || (gofmt -l . && exit 1)
